### ISSUE TITLE
Re-orient Tim on the original tim.js microscript?

### ISSUE THREAD

**Issue by premasagar** [premasagar/tim#17]
I worked on [tim2](https://github.com/premasagar/tim/tree/tim2) for a while, and the simplicity of both its code and its templating syntax was interesting, but it never really matured into a robust enough library.

I've continued to find the [original tim.js microscript](https://github.com/premasagar/tim/blob/master/tinytim.js) useful for simple templating, but with the advent of [handlebars](http://handlebarsjs.com/) and other templating libraries, I haven't felt too much need for the [extended tim.js](https://github.com/premasagar/tim/blob/master/tim.js).

I'd be glad to hear feedback on whether there's anything specifically useful about the full tim.js compared to other libraries.

**Comment by benpolinsky** [comment]
Hi!  
I picked up tim.js to inject a few config variables into .jsx when building a static site. While I do use handlebars for main templating, it would have been annoying (because, like handlebars, JSX also uses curly braces).

Works great.  If I continue to use it and don't find a need for additional features, I may write up some unit tests.

Didn't do _too_ much searching around, but tim.js seemed to fit my use-case, so I'm using it.

Thanks for the library.

**Comment by premasagar** [comment]
Thanks for your comment @benpolinsky. I'm glad you've found it useful.
